name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '24'
    - run: |
        echo "Running tests..."
        npm ci
        npm test
          

  build:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        docker build --file Dockerfile --tag jer3m/pdm-mcp-server:${{ github.sha }} .

        docker push jer3m/pdm-mcp-server:${{ github.sha }}
    
  
