name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        docker build --file Dockerfile --tag jer3m/pdm-mcp-server:${{ github.sha }} .

        docker push jer3m/pdm-mcp-server:${{ github.sha }}
    
  
